CREATE TABLE IF NOT EXISTS suscriptions(
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  cost DECIMAL(10, 2) NULL,
  active BOOLEAN NOT NULL DEFAULT 0,
  time_sucription_days INT NOT NULL, 
  type_suscription VARCHAR(10) NULL,
  PRIMARY KEY(id),
  UNIQUE KEY UQ_suscription_name(type_suscription)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS requests(
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  message_request VARCHAR(250) NULL,
  date_request DATETIME NULL,
  technical_id INT NOT NULL, 
  PRIMARY KEY(id)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS technical(
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  name_technical VARCHAR(50) NULL,
  lastname_technical VARCHAR(50) NULL,
  dni VARCHAR(10) NULL, 
  PRIMARY KEY(id),
  UNIQUE KEY UQ_technical_dni(dni)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

